// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LeaderboardUser } from "./LeaderboardUser";

export interface LeaderboardPlayer { money: number, stamina_lvl: number, regen_lvl: number, auto_lvl: number, user: LeaderboardUser, }