// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Player { money: number, stamina_lvl: number, regen_lvl: number, auto_lvl: number, stamina: number, can_breathe: boolean, can_sniff: boolean, }