// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { User } from "./User";

export interface Player { id: string, money: number, stamina_lvl: number, regen_lvl: number, auto_lvl: number, stamina: number, can_breathe: boolean, can_sniff: boolean, user: User | null, }