// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Stats { money: number, spent_money: number, playtime: number, out_of_breath: number, sniffed: number, }