name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 60

    env:
      RUST_VERSION: 1.67.0
      NODE_VERSION: 16
      GH_ACTIONS: true
      RUST_BACKTRACE: full
      ENC_KEY: ${{ secrets.ENC_KEY }}
      AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
      AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
      AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
      API_URL: ${{ secrets.API_URL }}
      TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
      TAURI_KEY_PASSWORD:

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ env.RUST_VERSION }}

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Get app version
        id: app_version
        uses: juliangruber/read-file-action@v1.1.6
        with:
          path: "src-tauri/tauri.conf.json"

      - name: Build application
        run: |
          cd ./src-tauri/
          cargo test
          cd ..
          yarn 
          yarn tauri build

      - name: Release App
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ fromJson(steps.app_version.outputs.content).package.version }}"
          files: |
            src-tauri/target/release/bundle/msi/ToulenSniffer_*.msi
            src-tauri/target/release/bundle/msi/ToulenSniffer_*.msi.zip

      - name: Get .sig file
        uses: juliangruber/read-file-action@v1.1.6
        id: sig
        with:
          path: "src-tauri/target/release/bundle/msi/ToulenSniffer_${{ fromJson(steps.app_version.outputs.content).package.version }}_x64_en-US.msi.zip.sig"

      - name: Get meta.json from gist
        uses: gorgbus/gist-actions@main
        id: gist_content
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          gist_id: "64160457f8144af815a94eca5fbc6be7"
          file_name: "meta.json"
          action: "get"

      - name: Edit meta.json version
        uses: gorgbus/edit-json-string@main
        id: new_gist_ver
        with:
          json_string: ${{ steps.gist_content.outputs.content }}
          field: "version"
          value: ${{ fromJson(steps.app_version.outputs.content).package.version }}

      - name: Edit meta.json sig
        uses: gorgbus/edit-json-string@main
        id: new_gist_sig
        with:
          json_string: ${{ steps.new_gist_ver.outputs.content }}
          field: "platforms.windows-x86_64.signature"
          value: ${{ fromJson(steps.sig.outputs.content).package.version }}

      - name: Edit meta.json download
        uses: gorgbus/edit-json-string@main
        id: new_gist
        with:
          json_string: ${{ steps.new_gist_sig.outputs.content }}
          field: "platforms.windows-x86_64.url"
          value: "https://github.com/gorgbus/toulen/releases/download/v${{ fromJson(steps.app_version.outputs.content).package.version }}/ToulenSniffer_${{ fromJson(steps.app_version.outputs.content).package.version }}_x64_en-US.msi.zip"

      - name: Update gist
        uses: gorgbus/gist-actions@main
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          gist_id: "64160457f8144af815a94eca5fbc6be7"
          file_name: "meta.json"
          content: ${{ steps.new_gist.outputs.content }}
          action: "update"
